[[BundleLoader]]
arch = "aarch64"
git-tree-sha1 = "3aae9ed35aa304d256aa3d25680d65c462344fd7"
os = "macos"

    [[BundleLoader.download]]
    sha256 = "00f34ee7356b3b05e3cc8ef4875e092392f2003cdd6c80e16c197d6e6cf59c33"
    url = "https://github.com/PumasAI/BundleLoader_jll.jl/releases/download/BundleLoader-v0.1.2+0/BundleLoader.v0.1.2.aarch64-apple-darwin.tar.gz"
[[BundleLoader]]
arch = "x86_64"
git-tree-sha1 = "f2e03ded5e0f67e8231d5b204cb997abae81a72c"
os = "macos"

    [[BundleLoader.download]]
    sha256 = "0a17f3e55709cb9b74d70e51831cf02844290ecc571dd91be10bdf00358b3da0"
    url = "https://github.com/PumasAI/BundleLoader_jll.jl/releases/download/BundleLoader-v0.1.2+0/BundleLoader.v0.1.2.x86_64-apple-darwin.tar.gz"
[[BundleLoader]]
arch = "x86_64"
git-tree-sha1 = "d1d0216c5d205ad71de4fb0897063112219f9780"
libc = "glibc"
os = "linux"

    [[BundleLoader.download]]
    sha256 = "5e7777bbc89fd5212976ce9c2de8645b64becb41159fdd2df98f30d58e47841d"
    url = "https://github.com/PumasAI/BundleLoader_jll.jl/releases/download/BundleLoader-v0.1.2+0/BundleLoader.v0.1.2.x86_64-linux-gnu.tar.gz"
[[BundleLoader]]
arch = "x86_64"
git-tree-sha1 = "4c422fb9e7565666e4dda901f60c6cd4d42c6b7b"
os = "windows"

    [[BundleLoader.download]]
    sha256 = "37458eaecf74b53394f2fe8a83e2f9de8b903de5647f79d7db7bfb3fb1af5577"
    url = "https://github.com/PumasAI/BundleLoader_jll.jl/releases/download/BundleLoader-v0.1.2+0/BundleLoader.v0.1.2.x86_64-w64-mingw32.tar.gz"
