# Autogenerated wrapper script for BundleLoader_jll for x86_64-linux-gnu
export libbundle_loader

JLLWrappers.@generate_wrapper_header("BundleLoader")
JLLWrappers.@declare_library_product(libbundle_loader, "libbundle_loader.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbundle_loader,
        "lib/libbundle_loader.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
