# Autogenerated wrapper script for BundleLoader_jll for x86_64-w64-mingw32
export libbundle_loader

using LicenseSpring_jll
JLLWrappers.@generate_wrapper_header("BundleLoader")
JLLWrappers.@declare_library_product(libbundle_loader, "bundle_loader.dll")
function __init__()
    JLLWrappers.@generate_init_header(LicenseSpring_jll)
    JLLWrappers.@init_library_product(
        libbundle_loader,
        "bin\\bundle_loader.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
